package com.paboomi.backend.model.visitor;

import com.paboomi.backend.antlr.generated.LatinParser;
import com.paboomi.backend.antlr.generated.LatinParserBaseVisitor;
import com.paboomi.backend.model.nodes.declaration.NodeDeclaration;
import com.paboomi.backend.model.nodes.literal.*;
import com.paboomi.backend.model.nodes.principal.ASTNode;
import com.paboomi.backend.model.nodes.declaration.NodeArrayDeclaration;
import com.paboomi.backend.model.nodes.declaration.NodeStructDefinition;
import com.paboomi.backend.model.nodes.declaration.NodeVariableDeclaration;
import com.paboomi.backend.model.nodes.expression.*;
import com.paboomi.backend.model.nodes.function.NodeFunction;
import com.paboomi.backend.model.nodes.function.NodeParameter;
import com.paboomi.backend.model.nodes.instruction.*;
import com.paboomi.backend.model.nodes.lvalue.NodeFieldAccess;
import com.paboomi.backend.model.nodes.lvalue.NodeIndexAccess;
import com.paboomi.backend.model.nodes.lvalue.NodeLvalue;
import com.paboomi.backend.model.nodes.principal.NodeProgram;

import java.util.ArrayList;
import java.util.List;

/**
 * ANTLR4 Visitor -> Custom AST.
 * Converts the Concrete Syntax Tree (CST) generated by ANTLR4 into the
 * Abstract Syntax Tree (AST) defined in package model.nodes.
 *
 * Each visit...Context method takes a CST node and returns the equivalent AST node
 */
public class ASTBuilder extends LatinParserBaseVisitor<ASTNode> {

    // ============================================================
    // ROOT PROGRAM
    // ============================================================

    @Override
    public ASTNode visitProgram(LatinParser.ProgramContext ctx) {
        NodeProgram program = new NodeProgram();

        if (ctx.globalDeclarations() != null) {
            for (LatinParser.GlobalDeclarationContext declCtx : ctx.globalDeclarations().globalDeclaration()) {
                ASTNode decl = visit(declCtx);
                if (decl instanceof NodeDeclaration) {
                    program.addGlobalDeclaration((NodeDeclaration) decl);
                }
            }
        }

        if (ctx.functionDefinitions() != null) {
            for (LatinParser.FunctionDefinitionContext funcCtx : ctx.functionDefinitions().functionDefinition()) {
                ASTNode func = visit(funcCtx);
                if (func != null) {
                    program.addFunctionDefinition(func);
                }
            }
        }

        if (ctx.mainInstructions() != null) {
            for (LatinParser.InstructionContext instCtx : ctx.mainInstructions().instruction()) {
                ASTNode inst = visit(instCtx);
                if (inst != null) {
                    program.addMainInstruction(inst);
                }
            }
        }

        return program;
    }

    @Override
    public ASTNode visitGlobalDeclarations(LatinParser.GlobalDeclarationsContext ctx) {
        List<ASTNode> declarations = new ArrayList<>();
        for (LatinParser.GlobalDeclarationContext declCtx : ctx.globalDeclaration()){
            ASTNode decl = visit(declCtx);
            if(decl != null) declarations.add(decl);
        }
        return (ASTNode) declarations;
    }

    @Override
    public ASTNode visitGlobalDeclarationDeclaration(LatinParser.GlobalDeclarationDeclarationContext ctx) {
        return visit(ctx.declaration());
    }

    @Override
    public ASTNode visitGlobalDeclarationArrayDeclaration(LatinParser.GlobalDeclarationArrayDeclarationContext ctx) {
        return visit(ctx.arrayDeclaration());
    }

    @Override
    public ASTNode visitGlobalDeclarationStructDefinition(LatinParser.GlobalDeclarationStructDefinitionContext ctx) {
        return visit(ctx.structDefinition());
    }

    @Override
    public ASTNode visitFunctionDefinitions(LatinParser.FunctionDefinitionsContext ctx) {
        return null;
    }

    @Override
    public ASTNode visitMainInstructions(LatinParser.MainInstructionsContext ctx) {
        return null;
    }


    // ============================================================
    // STATEMENTS
    // ============================================================

    @Override
    public ASTNode visitDeclaration(LatinParser.DeclarationContext ctx) {
        String id = ctx.ID().getText();
        String type = ctx.type() != null ? extractType(ctx.type()) : null;
        ASTNode initializer = ctx.expression() != null ? visit(ctx.expression()) : null;

        return new NodeVariableDeclaration(
                id,
                type,
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitArrayDeclaration(LatinParser.ArrayDeclarationContext ctx) {
        String id = ctx.ID().getText();
        ASTNode sizeExpr = visit(ctx.expression());
        String elementType = ctx.type() != null ? extractType(ctx.type()) : null;

        NodeArrayDeclaration arrDecl = new NodeArrayDeclaration(
                id,
                sizeExpr,
                elementType,
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        if (ctx.arrayValues() != null) {
            for (LatinParser.ExpressionContext exprCtx : ctx.arrayValues().expression()) {
                ASTNode value = visit(exprCtx);
                if (value != null) {
                    arrDecl.getInitialValues().add(value);
                }
            }
        }

        return arrDecl;
    }

    @Override
    public ASTNode visitStructDefinition(LatinParser.StructDefinitionContext ctx) {
        String id = ctx.ID().getText();
        NodeStructDefinition structDef = new NodeStructDefinition(
                id,
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        for (LatinParser.StructFieldDeclarationContext fieldCtx : ctx.structFieldDeclaration()) {
            ASTNode field = visit(fieldCtx);
            if (field != null) {
                structDef.addField(field);
            }
        }

        return structDef;
    }

    @Override
    public ASTNode visitStructFieldDeclarationVariables(LatinParser.StructFieldDeclarationVariablesContext ctx) {
        String id = ctx.ID().getText();
        String type = extractType(ctx.type());
        return new NodeVariableDeclaration(
                id,
                type,
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStructFieldDeclarationSeries(LatinParser.StructFieldDeclarationSeriesContext ctx) {
        String id = ctx.ID().getText();
        String type = extractType(ctx.type());
        return new NodeVariableDeclaration(
                id,
                "SERIES_" + type,
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // FUNCTIONS
    // ============================================================

    @Override
    public ASTNode visitFunctionDefinitionVoid(LatinParser.FunctionDefinitionVoidContext ctx) {
        return buildFunction(ctx.ID().getText(), null, ctx.parameterList(), ctx.functionBody(), ctx);
    }

    @Override
    public ASTNode visitFunctionDefinitionReturn(LatinParser.FunctionDefinitionReturnContext ctx) {
        String returnType = extractType(ctx.type());
        return buildFunction(ctx.ID().getText(), returnType, ctx.parameterList(), ctx.functionBody(), ctx);
    }

    private NodeFunction buildFunction(String name, String returnType,
            LatinParser.ParameterListContext paramListCtx,
            LatinParser.FunctionBodyContext bodyCtx,
            org.antlr.v4.runtime.ParserRuleContext ctx) {
        NodeFunction function = new NodeFunction(
                name,
                returnType,
                new ArrayList<>(),
                new ArrayList<>(),
                null,
                returnType == null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        if (paramListCtx != null) {
            for (LatinParser.ParameterContext paramCtx : paramListCtx.parameter()) {
                ASTNode param = visit(paramCtx);
                if (param != null) {
                    function.addParameter((NodeParameter) param);
                }
            }
        }

        NodeBlock body = new NodeBlock(ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
        if (bodyCtx != null) {
            if (bodyCtx.varSection() != null) {
                for (LatinParser.DeclarationContext declCtx : bodyCtx.varSection().declaration()) {
                    ASTNode decl = visit(declCtx);
                    if (decl instanceof NodeDeclaration) {
                        function.addLocalVariable((NodeDeclaration) decl);
                    }
                }
            }
            for (LatinParser.InstructionContext instCtx : bodyCtx.instruction()) {
                ASTNode inst = visit(instCtx);
                if (inst != null) {
                    body.addInstruction(inst);
                }
            }
        }

        function.setBody(body);
        return function;
    }

    @Override
    public ASTNode visitParameter(LatinParser.ParameterContext ctx) {
        String id = ctx.ID().getText();
        String type = extractType(ctx.type());
        return new NodeParameter(
                id,
                type,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // INSTRUCTIONS
    // ============================================================

    @Override
    public ASTNode visitInstructionAssignment(LatinParser.InstructionAssignmentContext ctx) {
        if (ctx.assignment() != null)
            return visit(ctx.assignment());
        if (ctx.readStatement() != null)
            return visit(ctx.readStatement());
        if (ctx.printStatement() != null)
            return visit(ctx.printStatement());
        if (ctx.ifStatement() != null)
            return visit(ctx.ifStatement());
        if (ctx.whileStatement() != null)
            return visit(ctx.whileStatement());
        if (ctx.doWhileStatement() != null)
            return visit(ctx.doWhileStatement());
        if (ctx.forStatement() != null)
            return visit(ctx.forStatement());
        if (ctx.jumpStatement() != null)
            return visit(ctx.jumpStatement());
        if (ctx.returnStatement() != null)
            return visit(ctx.returnStatement());
        if (ctx.expression() != null)
            return visit(ctx.expression());
        return null;
    }

    @Override
    public ASTNode visitAssignment(LatinParser.AssignmentContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitReadStatement(LatinParser.ReadStatementContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        return new NodeRead(
                lvalue,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintStatement(LatinParser.PrintStatementContext ctx) {
        NodePrint print = new NodePrint(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.PrintItemContext itemCtx : ctx.printItem()) {
            ASTNode item = visit(itemCtx);
            if (item != null) {
                print.addPrintItem(item);
            }
        }
        return print;
    }

    @Override
    public ASTNode visitPrintItemString(LatinParser.PrintItemStringContext ctx) {
        return new NodeStringLiteral(
                ctx.STRING().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintItemID(LatinParser.PrintItemIDContext ctx) {
        return new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintItemExpression(LatinParser.PrintItemExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitIfStatement(LatinParser.IfStatementContext ctx) {
        ASTNode conditionNode = visit(ctx.booleanExpression());
        NodeBooleanExpression condition = wrapBoolean(conditionNode, ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        NodeBlock thenBlock = asBlock(visit(ctx.block()));

        NodeIf nodeIf = new NodeIf(
                condition,
                thenBlock,
                new ArrayList<>(),
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        //* else if clauses
        for (LatinParser.ElseIfClauseContext elseIfCtx : ctx.elseIfClause()) {
            ASTNode elseConditionNode = visit(elseIfCtx.booleanExpression());
            NodeBooleanExpression elseCondition = wrapBoolean(elseConditionNode, elseIfCtx.getStart().getLine(),
                    elseIfCtx.getStart().getCharPositionInLine());
            NodeBlock elseIfBlock = asBlock(visit(elseIfCtx.block()));
            nodeIf.addElseIfClause(elseCondition, elseIfBlock);
        }

        //* else clause
        if (ctx.elseClause() != null) {
            nodeIf.setElseBlock(asBlock(visit(ctx.elseClause())));
        }

        return nodeIf;
    }

    @Override
    public ASTNode visitElseIfClause(LatinParser.ElseIfClauseContext ctx) {
        return null;
    }

    @Override
    public ASTNode visitElseClause(LatinParser.ElseClauseContext ctx) {
        return visit(ctx.block());
    }

    @Override
    public ASTNode visitWhileStatement(LatinParser.WhileStatementContext ctx) {
        ASTNode conditionNode = visit(ctx.booleanExpression());
        NodeBooleanExpression condition = wrapBoolean(conditionNode, ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        NodeBlock block = asBlock(visit(ctx.block()));
        return new NodeWhile(
                condition,
                block,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitDoWhileStatement(LatinParser.DoWhileStatementContext ctx) {
        NodeBlock block = asBlock(visit(ctx.block()));
        ASTNode conditionNode = visit(ctx.booleanExpression());
        NodeBooleanExpression condition = wrapBoolean(conditionNode, ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        return new NodeDoWhile(
                block,
                condition,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForStandard(LatinParser.ForStandardContext ctx) {
        ASTNode init = ctx.forInit() != null ? visit(ctx.forInit()) : null;
        ASTNode conditionNode = ctx.forCondition() != null ? visit(ctx.forCondition()) : null;
        NodeBooleanExpression condition = conditionNode != null
                ? wrapBoolean(conditionNode, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine())
                : null;
        ASTNode update = ctx.forUpdate() != null ? visit(ctx.forUpdate()) : null;
        NodeBlock block = asBlock(visit(ctx.block()));

        return new NodeFor(
                init,
                condition,
                update,
                block,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitWithDeclaration(LatinParser.ForInitWithDeclarationContext ctx) {
        String id = ctx.ID().getText();
        String type = ctx.type() != null ? extractType(ctx.type()) : null;
        ASTNode initializer = ctx.expression() != null ? visit(ctx.expression()) : null;
        return new NodeVariableDeclaration(
                id,
                type,
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitWithAssign(LatinParser.ForInitWithAssignContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitWithID(LatinParser.ForInitWithIDContext ctx) {
        return new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForUpdateExpression(LatinParser.ForUpdateExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitForUpdateLvalue(LatinParser.ForUpdateLvalueContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitJumpStatementContinue(LatinParser.JumpStatementContinueContext ctx) {
        return new NodeContinue(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitJumpStatementReturn(LatinParser.JumpStatementReturnContext ctx) {
        return new NodeBreak(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitReturnStatement(LatinParser.ReturnStatementContext ctx) {
        ASTNode expression = ctx.expression() != null ? visit(ctx.expression()) : null;
        return new NodeReturn(
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitBlock(LatinParser.BlockContext ctx) {
        NodeBlock block = new NodeBlock(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.InstructionContext instCtx : ctx.instruction()) {
            ASTNode inst = visit(instCtx);
            if (inst != null) {
                block.addInstruction(inst);
            }
        }
        return block;
    }

    // ============================================================
    // LVALUE assignable values
    // ============================================================

    @Override
    public ASTNode visitLvalue(LatinParser.LvalueContext ctx) {
        NodeLvalue lvalue = new NodeLvalue(
                ctx.ID().getText(),
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        for (LatinParser.LvalueSufixContext suffixCtx : ctx.lvalueSufix()) {
            ASTNode suffix = visit(suffixCtx);
            if (suffix != null) {
                lvalue.addSuffix(suffix);
            }
        }

        return lvalue;
    }

    @Override
    public ASTNode visitFieldAccess(LatinParser.FieldAccessContext ctx) {
        return new NodeFieldAccess(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitIndexAccess(LatinParser.IndexAccessContext ctx) {
        ASTNode index = visit(ctx.expression());
        return new NodeIndexAccess(
                index,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // GENERAL EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitExpressionBooleanExpression(LatinParser.ExpressionBooleanExpressionContext ctx) {
        return visit(ctx.booleanExpression());
    }

    @Override
    public ASTNode visitExpressionNumericExpression(LatinParser.ExpressionNumericExpressionContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitExpressionStringExpression(LatinParser.ExpressionStringExpressionContext ctx) {
        return visit(ctx.stringExpression());
    }

    @Override
    public ASTNode visitExpressionStructLiteral(LatinParser.ExpressionStructLiteralContext ctx) {
        return visit(ctx.structLiteral());
    }

    @Override
    public ASTNode visitExpressionArrayCreation(LatinParser.ExpressionArrayCreationContext ctx) {
        return visit(ctx.arrayCreation());
    }

    @Override
    public ASTNode visitExpressionArrayLiteral(LatinParser.ExpressionArrayLiteralContext ctx) {
        return visit(ctx.arrayLiteral());
    }

    @Override
    public ASTNode visitNumericLiteralChar(LatinParser.NumericLiteralCharContext ctx) {
        String text = ctx.CHAR().getText();
        char value = text.length() >= 3 ? text.charAt(1) : '\0';
        return new NodeIntegerLiteral(
                (int) value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitNumericLiteralBoolean(LatinParser.NumericLiteralBooleanContext ctx) {
        boolean value = ctx.booleanLiteral() instanceof LatinParser.BooleanLiteralVerumContext;
        return new NodeIntegerLiteral(
                value ? 1 : 0,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    // ============================================================
    // BOOLEAN EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitBooleanExpression(LatinParser.BooleanExpressionContext ctx) {
        /*ASTNode expression = visit(ctx.booleanOrExpression());
        return new NodeBooleanExpression(expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
         */
        return visit(ctx.booleanOrExpression());
    }

    @Override
    public ASTNode visitBooleanOrExpression(LatinParser.BooleanOrExpressionContext ctx) {
        List<LatinParser.BooleanAndExpressionContext> operands = ctx.booleanAndExpression();
        ASTNode left = visit(operands.get(0));
        for (int i = 1; i < operands.size(); i++) {
            ASTNode right = visit(operands.get(i));
            left = new NodeBinaryOperation(
                    left,
                    "||",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitBooleanAndExpression(LatinParser.BooleanAndExpressionContext ctx) {
        List<LatinParser.ComparisonExpressionContext> operands = ctx.comparisonExpression();
        ASTNode left = visit(operands.get(0));
        for (int i = 1; i < operands.size(); i++) {
            ASTNode right = visit(operands.get(i));
            left = new NodeBinaryOperation(
                    left,
                    "&&",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitComparisonExpressionNot(LatinParser.ComparisonExpressionNotContext ctx) {
        ASTNode operand = visit(ctx.comparisonExpression());
        return new NodeUnaryOperation(
                "!",
                operand,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitComparisonExpressionComparisonOperand(
            LatinParser.ComparisonExpressionComparisonOperandContext ctx) {
        if (ctx.comparisonOperand().size() == 1) {
            return visit(ctx.comparisonOperand(0));
        }
        ASTNode left = visit(ctx.comparisonOperand(0));
        ASTNode right = visit(ctx.comparisonOperand(1));
        String operator = extractRelationalOperator(ctx.relationalLiteral());
        return new NodeBinaryOperation(
                left,
                operator,
                right,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitComparisonExpressionBooleanExpresion(
            LatinParser.ComparisonExpressionBooleanExpresionContext ctx) {
        return visit(ctx.booleanExpression());
    }

    @Override
    public ASTNode visitComparisonOperand(LatinParser.ComparisonOperandContext ctx) {
        if (ctx.numericExpression() != null)
            return visit(ctx.numericExpression());
        if (ctx.booleanLiteral() != null)
            return visit(ctx.booleanLiteral());
        if (ctx.stringExpression() != null)
            return visit(ctx.stringExpression());
        return null;
    }


    // ============================================================
    // NUMERIC EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitNumericExpression(LatinParser.NumericExpressionContext ctx) {
        return visit(ctx.additiveExpression());
    }

    @Override
    public ASTNode visitAdditiveExpression(LatinParser.AdditiveExpressionContext ctx) {
        List<LatinParser.MultiplicativeExpressionContext> operands = ctx.multiplicativeExpression();
        List<LatinParser.PlusMinusExpressionContext> operators = ctx.plusMinusExpression();

        ASTNode left = visit(operands.get(0));
        for (int i = 0; i < operators.size(); i++) {
            String op = extractPlusMinusOperator(operators.get(i));
            ASTNode right = visit(operands.get(i + 1));
            left = new NodeBinaryOperation(
                    left,
                    op,
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitMultiplicativeExpression(LatinParser.MultiplicativeExpressionContext ctx) {
        List<LatinParser.UnaryExpressionContext> operands = ctx.unaryExpression();
        List<LatinParser.MultSplitExpressionContext> operators = ctx.multSplitExpression();

        ASTNode left = visit(operands.get(0));
        for (int i = 0; i < operators.size(); i++) {
            String op = extractMultSplitOperator(operators.get(i));
            ASTNode right = visit(operands.get(i + 1));
            left = new NodeBinaryOperation(
                    left,
                    op,
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitUnaryExpressionAddSub(LatinParser.UnaryExpressionAddSubContext ctx) {
        String op = extractAddSubOperator(ctx.addSubExpression());
        ASTNode operand = visit(ctx.unaryExpression());
        return new NodeUnaryOperation(
                op,
                operand,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitUnaryExpressionNumeric(LatinParser.UnaryExpressionNumericContext ctx) {
        return visit(ctx.primaryNumeric());
    }

    @Override
    public ASTNode visitPrimaryNumericNumericLiteral(LatinParser.PrimaryNumericNumericLiteralContext ctx) {
        return visit(ctx.numericLiteral());
    }

    @Override
    public ASTNode visitPrimaryNumericAtributeAccessExpression(
            LatinParser.PrimaryNumericAtributeAccessExpressionContext ctx) {
        NodeIdentifier base = new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        return buildAccessChain(base, ctx.atributeAccessExpresion());
    }

    @Override
    public ASTNode visitPrimaryNumericNumericExpression(LatinParser.PrimaryNumericNumericExpressionContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitNumericLiteralInteger(LatinParser.NumericLiteralIntegerContext ctx) {
        return new NodeIntegerLiteral(
                Integer.parseInt(ctx.INTEGER().getText()),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitNumericLiteralDecimal(LatinParser.NumericLiteralDecimalContext ctx) {
        return new NodeDecimalLiteral(
                Double.parseDouble(ctx.DECIMAL().getText()),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // STRING EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitStringExpression(LatinParser.StringExpressionContext ctx) {
        return visit(ctx.stringAdditiveExpression());
    }

    @Override
    public ASTNode visitStringAdditiveExpression(LatinParser.StringAdditiveExpressionContext ctx) {
        ASTNode left = visit(ctx.stringPrimary());
        for (LatinParser.StringAdditiveItemContext itemCtx : ctx.stringAdditiveItem()) {
            ASTNode right = visit(itemCtx);
            left = new NodeBinaryOperation(
                    left,
                    "+",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitStringAdditiveItemStringPrimary(LatinParser.StringAdditiveItemStringPrimaryContext ctx) {
        return visit(ctx.stringPrimary());
    }

    @Override
    public ASTNode visitStringAdditiveItemNumericExpression(
            LatinParser.StringAdditiveItemNumericExpressionContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitStringPrimaryString(LatinParser.StringPrimaryStringContext ctx) {
        return new NodeStringLiteral(
                ctx.STRING().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStringPrimaryChar(LatinParser.StringPrimaryCharContext ctx) {
        String text = ctx.CHAR().getText();
        char value = text.length() >= 3 ? text.charAt(1) : '\0';
        return new NodeCharLiteral(
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStringPrimaryAtributeAccessExpression(
            LatinParser.StringPrimaryAtributeAccessExpressionContext ctx) {
        NodeIdentifier base = new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        return buildAccessChain(base, ctx.atributeAccessExpresion());
    }

    // ============================================================
    // BOOLEAN LITERALS
    // ============================================================

    @Override
    public ASTNode visitBooleanLiteralVerum(LatinParser.BooleanLiteralVerumContext ctx) {
        return new NodeBooleanLiteral(
                true,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitBooleanLiteralFalsus(LatinParser.BooleanLiteralFalsusContext ctx) {
        return new NodeBooleanLiteral(
                false,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    //    Attribute access, indexing, and function calls
    // ============================================================

    @Override
    public ASTNode visitAtributeAccessExpressionDitID(LatinParser.AtributeAccessExpressionDitIDContext ctx) {
        return new NodeFieldAccess(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitAtributeAccessExpressionClaspExpression(
            LatinParser.AtributeAccessExpressionClaspExpressionContext ctx) {
        ASTNode index = visit(ctx.expression());
        return new NodeIndexAccess(
                index,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitAtributeAccessExpressionParenExpression(
            LatinParser.AtributeAccessExpressionParenExpressionContext ctx) {
        List<ASTNode> args = new ArrayList<>();
        if (ctx.argumentList() != null) {
            for (LatinParser.ExpressionContext exprCtx : ctx.argumentList().expression()) {
                ASTNode arg = visit(exprCtx);
                if (arg != null) {
                    args.add(arg);
                }
            }
        }
        return new NodeFunctionCall(
                null,
                args,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // STRUCT LITERALS
    // ============================================================

    @Override
    public ASTNode visitStructLiteral(LatinParser.StructLiteralContext ctx) {
        String typeName = ctx.ID() != null ? ctx.ID().getText() : null;
        NodeStructLiteral structLit = new NodeStructLiteral(
                typeName,
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.StructFieldInitializerContext initCtx : ctx.structFieldInitializer()) {
            ASTNode init = visit(initCtx);
            if (init != null) {
                structLit.addFieldInitializer((NodeStructFieldInitializer) init);
            }
        }
        return structLit;
    }

    @Override
    public ASTNode visitStructFieldInitializer(LatinParser.StructFieldInitializerContext ctx) {
        String fieldName = ctx.ID().getText();
        ASTNode value = visit(ctx.expression());
        return new NodeStructFieldInitializer(
                fieldName,
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // ARRAY CREATION AND ARRAY LITERAL
    // ============================================================

    @Override
    public ASTNode visitArrayCreation(LatinParser.ArrayCreationContext ctx) {
        String elementType = extractType(ctx.type());
        ASTNode size = visit(ctx.expression());
        return new NodeArrayCreation(
                elementType,
                size,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitArrayLiteral(LatinParser.ArrayLiteralContext ctx) {
        NodeArrayLiteral arrLit = new NodeArrayLiteral(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.ExpressionContext exprCtx : ctx.expression()) {
            ASTNode value = visit(exprCtx);
            if (value != null) {
                arrLit.addValue(value);
            }
        }
        return arrLit;
    }

    private static NodeLvalue asLvalue(ASTNode node) {
        return (node instanceof NodeLvalue) ? (NodeLvalue) node : null;
    }

    private static NodeBlock asBlock(ASTNode node) {
        return (node instanceof NodeBlock) ? (NodeBlock) node : null;
    }

    private static NodeBooleanExpression wrapBoolean(ASTNode node, int line, int column) {
        if (node instanceof NodeBooleanExpression) {
            return (NodeBooleanExpression) node;
        }
        return new NodeBooleanExpression(node, line, column);
    }

    // ============================================================
    //  HELPER METHODS
    // ============================================================

    private String extractType(LatinParser.TypeContext ctx) {
        if (ctx == null)
            return null;
        if (ctx instanceof LatinParser.TypeNumerusContext)
            return "NUMERUS";
        if (ctx instanceof LatinParser.TypeTextumContext)
            return "TEXTUM";
        if (ctx instanceof LatinParser.TypeDecimalisContext)
            return "DECIMALIS";
        if (ctx instanceof LatinParser.TypeLitteraContext)
            return "LITTERA";
        if (ctx instanceof LatinParser.TypeVerumContext)
            return "VERUM";
        if (ctx instanceof LatinParser.TypeFalsusContext)
            return "FALSUS";
        if (ctx instanceof LatinParser.TypeIDContext)
            return ctx.getText();
        if (ctx instanceof LatinParser.TypeBoolContext)
            return "BOOL";
        return null;
    }

    private String extractRelationalOperator(LatinParser.RelationalLiteralContext ctx) {
        if (ctx == null)
            return "==";
        if (ctx instanceof LatinParser.RelationalLiteralIdenticContext)
            return "==";
        if (ctx instanceof LatinParser.RelationalLiteralDiffContext)
            return "!=";
        if (ctx instanceof LatinParser.RelationalLiteralMinorContext)
            return "<";
        if (ctx instanceof LatinParser.RelationalLiteralMajorContext)
            return ">";
        if (ctx instanceof LatinParser.RelationalLiteralMinorToContext)
            return "<=";
        if (ctx instanceof LatinParser.RelationalLiteralMajorToContext)
            return ">=";
        return "==";
    }

    private String extractPlusMinusOperator(LatinParser.PlusMinusExpressionContext ctx) {
        if (ctx == null)
            return "+";
        if (ctx instanceof LatinParser.PlusMinusExpressionPlusContext)
            return "+";
        if (ctx instanceof LatinParser.PlusMinusExpressionMinusContext)
            return "-";
        return "+";
    }

    private String extractMultSplitOperator(LatinParser.MultSplitExpressionContext ctx) {
        if (ctx == null)
            return "*";
        if (ctx instanceof LatinParser.MultSplitExpressionMultContext)
            return "*";
        if (ctx instanceof LatinParser.MultSplitExpressionSplitContext)
            return "/";
        return "*";
    }

    private String extractAddSubOperator(LatinParser.AddSubExpressionContext ctx) {
        if (ctx == null)
            return "+";
        if (ctx instanceof LatinParser.AddSubExpressionPlusContext)
            return "+";
        if (ctx instanceof LatinParser.AddSubExpressionMinusContext)
            return "-";
        if (ctx instanceof LatinParser.AddSubExpressionAddContext)
            return "+";
        if (ctx instanceof LatinParser.AddSubExpressionSubContext)
            return "-";
        return "+";
    }

    private ASTNode buildAccessChain(NodeIdentifier base,
                                     List<LatinParser.AtributeAccessExpresionContext> suffixes) {

        // Si no hay sufijos, devolvemos el identificador base tal cual
        if (suffixes == null || suffixes.isEmpty()) {
            return base;
        }

        // Creamos un NodeLvalue que es capaz de almacenar una lista plana de sufijos (campos e índices)
        NodeLvalue currentLvalue = new NodeLvalue(
                base.getId(),
                new ArrayList<>(),
                base.getLine(),
                base.getColumn());

        ASTNode currentExpression = currentLvalue;

        for (LatinParser.AtributeAccessExpresionContext suffix : suffixes) {
            if (suffix instanceof LatinParser.AtributeAccessExpressionDitIDContext) {
                String fieldName = ((LatinParser.AtributeAccessExpressionDitIDContext) suffix).ID().getText();

                if (currentExpression instanceof NodeLvalue) {
                    // Si seguimos en una cadena de Lvalue, agregamos el sufijo nativo NodeFieldAccess
                    currentLvalue.addSuffix(new NodeFieldAccess(fieldName, suffix.getStart().getLine(), suffix.getStart().getCharPositionInLine()));
                } else {
                    // Si ya hubo una llamada a función antes, lo tratamos como NodeAttributeAccess clásico
                    currentExpression = new NodeAttributeAccess(currentExpression, fieldName, suffix.getStart().getLine(), suffix.getStart().getCharPositionInLine());
                }

            } else if (suffix instanceof LatinParser.AtributeAccessExpressionClaspExpressionContext) {
                ASTNode index = visit(((LatinParser.AtributeAccessExpressionClaspExpressionContext) suffix).expression());

                if (currentExpression instanceof NodeLvalue) {
                    // Si seguimos en una cadena de Lvalue, agregamos el sufijo nativo NodeIndexAccess
                    currentLvalue.addSuffix(new NodeIndexAccess(index, suffix.getStart().getLine(), suffix.getStart().getCharPositionInLine()));
                } else {
                    currentExpression = new NodeAttributeAccess(currentExpression, index, suffix.getStart().getLine(), suffix.getStart().getCharPositionInLine());
                }

            } else if (suffix instanceof LatinParser.AtributeAccessExpressionParenExpressionContext) {
                LatinParser.AtributeAccessExpressionParenExpressionContext parenCtx = (LatinParser.AtributeAccessExpressionParenExpressionContext) suffix;
                List<ASTNode> args = new ArrayList<>();
                if (parenCtx.argumentList() != null) {
                    for (LatinParser.ExpressionContext exprCtx : parenCtx.argumentList().expression()) {
                        ASTNode arg = visit(exprCtx);
                        if (arg != null) {
                            args.add(arg);
                        }
                    }
                }
                String functionName = extractFunctionName(currentExpression);
                currentExpression = new NodeFunctionCall(
                        functionName,
                        args,
                        suffix.getStart().getLine(),
                        suffix.getStart().getCharPositionInLine());
            }
        }

        return currentExpression;
    }

    private String extractFunctionName(ASTNode node) {
        if (node instanceof NodeIdentifier) {
            return ((NodeIdentifier) node).getId();
        }
        if (node instanceof NodeAttributeAccess) {
            return ((NodeAttributeAccess) node).getFieldName();
        }
        // NUEVO: Extraer el nombre de la función si viene de un NodeLvalue
        if (node instanceof NodeLvalue) {
            NodeLvalue lval = (NodeLvalue) node;
            if (!lval.hasSuffixes()) {
                return lval.getIdentifier();
            } else {
                ASTNode lastSuffix = lval.getSuffixes().get(lval.getSuffixes().size() - 1);
                if (lastSuffix instanceof NodeFieldAccess) {
                    return ((NodeFieldAccess) lastSuffix).getFieldName();
                }
            }
        }
        return null;
    }
}
