package com.paboomi.frontend.gui;

import com.paboomi.backend.dtos.CustomErrorDTO;
import com.paboomi.backend.services.ServiceAnalyzer;
import com.paboomi.backend.services.TreeMapperService;
import com.paboomi.frontend.facade.FacadeCompilator;
import com.paboomi.frontend.facade.dto.AnalysisResultDTO;
import com.paboomi.frontend.gui.animation.TreeRouteAnimator;
import com.paboomi.frontend.gui.components.TextLineNumber;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author clare
 */
public class PrincipalWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalWindow.class.getName());
    private final Font codeFont = new Font("Consolas", Font.PLAIN, 14);
    private final FacadeCompilator facade;
    private JTree treeAST;
    private TreeRouteAnimator treeAnimator;

    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {

        // Initialize facade
        ServiceAnalyzer analyzer = new ServiceAnalyzer();
        TreeMapperService mapper = new TreeMapperService();
        this.facade = new FacadeCompilator(analyzer, mapper);

        initComponents();
        setupCustomComponents();

        // Color Palette
        Color bgEditor = new Color(30, 30, 46);       // Dark blue background
        Color fgEditor = new Color(205, 214, 244);     // Soft white
        Color currentLineBg = new Color(49, 50, 68);   // Active line fund
        Color lineNumbersFg = new Color(108, 112, 134); // Line numbers turned off
        Color currentLineFg = new Color(245, 194, 231); // Neon pink/purple for the current line
        Color bgConsola = new Color(24, 24, 37);       // Darker console background

        // Code Editor
        txtACodeEditor.setFont(codeFont);
        txtACodeEditor.setTabSize(4);
        txtACodeEditor.setBackground(bgEditor);
        txtACodeEditor.setForeground(fgEditor);
        txtACodeEditor.setCaretColor(new java.awt.Color(245, 224, 220)); // Glowing cursor
        txtACodeEditor.setSelectionColor(new java.awt.Color(69, 71, 90)); // Text selection color

        // This code shows the lines number in the code editor
        TextLineNumber lineNumber = new TextLineNumber(txtACodeEditor);
        lineNumber.setFont(txtACodeEditor.getFont());
        lineNumber.setBackground(bgEditor);
        lineNumber.setForeground(lineNumbersFg);
        lineNumber.setCurrentLineForeground(currentLineFg); // Color of the line where the cursor is located
        jScrollPane1.setRowHeaderView(lineNumber);
        
        // Console Style
        jTextArea2.setBackground(bgConsola);
        jTextArea2.setForeground(new java.awt.Color(166, 227, 161)); // Green terminal for outputs
        txtFCommandConsole.setBackground(bgConsola);
        txtFCommandConsole.setForeground(fgEditor);
        
        // Highlight stack buttons
        jButton1.setBackground(new java.awt.Color(137, 180, 250)); // Soft blue
        jButton1.setForeground(java.awt.Color.BLACK);
        jButton2.setBackground(new java.awt.Color(243, 139, 168)); // Soft Pink
        jButton2.setForeground(java.awt.Color.BLACK);

        // Estyle for the State Bar
        lblStateBar.setBackground(new java.awt.Color(17, 17, 27));
        lblStateBar.setForeground(new java.awt.Color(147, 153, 178));
        lblStateBar.setText(" Status: Ready | Mode: Editing ");

        // Clean bordered
        jSplitPane1.setBorder(null);
        jSplitPane2.setBorder(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlCodeEditor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtACodeEditor = new javax.swing.JTextArea();
        pnlConsole = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtFCommandConsole = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlStackViewer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlAST = new javax.swing.JPanel();
        pnlSymbolTable = new javax.swing.JPanel();
        pnlErrorReport = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblErrorReport = new javax.swing.JTable();
        pnlTranslatedCode = new javax.swing.JPanel();
        lblStateBar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCompile = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1225, 850));
        setPreferredSize(new java.awt.Dimension(1225, 850));
        setSize(new java.awt.Dimension(1225, 850));

        jSplitPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        jSplitPane2.setDividerLocation(500);
        jSplitPane2.setToolTipText("");

        jSplitPane1.setDividerLocation(425);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnlCodeEditor.setMinimumSize(new java.awt.Dimension(425, 300));
        pnlCodeEditor.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlCodeEditor.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        txtACodeEditor.setColumns(20);
        txtACodeEditor.setRows(5);
        jScrollPane1.setViewportView(txtACodeEditor);

        pnlCodeEditor.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setTopComponent(pnlCodeEditor);

        pnlConsole.setLayout(new java.awt.BorderLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        pnlConsole.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        txtFCommandConsole.setText("Enter the command");
        txtFCommandConsole.addActionListener(this::txtFCommandConsoleActionPerformed);
        pnlConsole.add(txtFCommandConsole, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(pnlConsole);

        jSplitPane2.setLeftComponent(jSplitPane1);

        pnlStackViewer.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Previous");
        jPanel4.add(jButton1);

        jButton2.setText("Next");
        jPanel4.add(jButton2);

        pnlStackViewer.add(jPanel4, java.awt.BorderLayout.NORTH);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        pnlStackViewer.add(jScrollPane3, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Stack", pnlStackViewer);

        pnlAST.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("AST", pnlAST);

        pnlSymbolTable.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Symbol Table", pnlSymbolTable);

        pnlErrorReport.setLayout(new java.awt.BorderLayout());

        tblErrorReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblErrorReport);

        pnlErrorReport.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Error's Report", pnlErrorReport);
        jTabbedPane1.addTab("Translated Code", pnlTranslatedCode);

        jSplitPane2.setRightComponent(jTabbedPane1);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        lblStateBar.setText("jLabel1");
        getContentPane().add(lblStateBar, java.awt.BorderLayout.SOUTH);

        jPanel1.setMinimumSize(new java.awt.Dimension(80, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 50));

        btnCompile.setText("Compile");
        btnCompile.addActionListener(this::btnCompileActionPerformed);
        jPanel1.add(btnCompile);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFCommandConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCommandConsoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCommandConsoleActionPerformed

    private void btnCompileActionPerformed(java.awt.event.ActionEvent evt) {                                           
        onCompileExecuted();
    }

    private void setupCustomComponents() {
        treeAST = new JTree();
        treeAST.setModel(null); // Inicia vacío
        treeAST.setBackground(new Color(30, 30, 46));

        JScrollPane treeScrollPane = new JScrollPane(treeAST);
        treeScrollPane.setBorder(null);

        pnlAST.setLayout(new BorderLayout());
        pnlAST.add(treeScrollPane, BorderLayout.CENTER);

        //treeAnimator = new TreeRouteAnimator(treeAST);

        // Configure JTable Errors
        pnlErrorReport.removeAll();
        pnlErrorReport.setLayout(new BorderLayout());

        if(tblErrorReport == null){ tblErrorReport = new JTable(); }

        //Allow resize columns manually
        tblErrorReport.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Force reordering header
        tblErrorReport.getTableHeader().setReorderingAllowed(false);
        tblErrorReport.getTableHeader().setResizingAllowed(true);

        JScrollPane errorScrollPane = new JScrollPane(tblErrorReport);
        errorScrollPane.setBorder(null);

        // Ensure the header viewport is always active
        errorScrollPane.setColumnHeaderView(tblErrorReport.getTableHeader());

        pnlErrorReport.add(errorScrollPane, BorderLayout.CENTER);

    }

    private void onCompileExecuted() {
        String code = txtACodeEditor.getText();

        if (code == null || code.trim().isEmpty()) {
            jTextArea2.setText("[SYSTEM]: Source code is empty.");
            return;
        }

        // Execute analyze with facade
        AnalysisResultDTO result = facade.codeAnalyze(code);

        if (result.isValid()) {
            jTextArea2.setText(">>> Compilation finished successfully. No syntax errors.\n");
            lblStateBar.setText(" Status: Success | Code parsed without errors ");

            // Clean errors table
            renderErrorsTable(List.of(), tblErrorReport);

            // Assign the new generated tree model to the JTree.
            treeAST.setModel(result.getTreeModel());

            // Expand all branches
            for (int i = 0; i < treeAST.getRowCount(); i++) {
                treeAST.expandRow(i);
            }

            // Dynamically switch to the AST tab.
            jTabbedPane1.setSelectedComponent(pnlAST);

            // Start the route animation (node every 400ms)
            //treeAnimator.startAnimation(400);

        } else {
            // Show compilation errors captured by ANTLR4
            jTextArea2.setText(">>> Compilation failed with " +
                    result.getErrorsList().size() +
                    " error(s).\nCheck the Error's Report tab");
            lblStateBar.setText(" Status: Failed | Errors found during compilation ");

            // Renderer errors in jtable
            renderErrorsTable(result.getErrorsList(), tblErrorReport);

            // Switch to the Error's Report tab automatically
            jTabbedPane1.setSelectedComponent(pnlErrorReport);
        }
    }

    public void renderErrorsTable(List<CustomErrorDTO> errors, JTable tblErrors) {
        // Define columns
        String[] columnNames = {"Line", "Column", "Error Description"};

        // Create table model non-editable
        DefaultTableModel model = new DefaultTableModel(columnNames, 0){
          @Override
          public boolean isCellEditable(int row, int column) {return false;}
        };

        for (CustomErrorDTO error : errors) {
            Object[] rowData = {
                    error.line(),
                    error.column(),
                    error.message()
            };
            model.addRow(rowData);
        }

        tblErrors.setModel(model);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < tblErrors.getColumnCount(); i++) {
            tblErrors.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Column "Line"
        tblErrors.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblErrors.getColumnModel().getColumn(0).setMinWidth(50);
        tblErrors.getColumnModel().getColumn(0).setMaxWidth(80);

        // Column "Line"
        tblErrors.getColumnModel().getColumn(1).setPreferredWidth(40);
        tblErrors.getColumnModel().getColumn(1).setMinWidth(50);
        tblErrors.getColumnModel().getColumn(1).setMaxWidth(80);

        // Column "Error Description"
        tblErrors.getColumnModel().getColumn(2).setPreferredWidth(600);
        tblErrors.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

        tblErrors.revalidate();
        tblErrors.repaint();


    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblStateBar;
    private javax.swing.JPanel pnlAST;
    private javax.swing.JPanel pnlCodeEditor;
    private javax.swing.JPanel pnlConsole;
    private javax.swing.JPanel pnlErrorReport;
    private javax.swing.JPanel pnlStackViewer;
    private javax.swing.JPanel pnlSymbolTable;
    private javax.swing.JPanel pnlTranslatedCode;
    private javax.swing.JTable tblErrorReport;
    private javax.swing.JTextArea txtACodeEditor;
    private javax.swing.JTextField txtFCommandConsole;
    // End of variables declaration//GEN-END:variables
}
